### ISSUE TITLE
I have no idea how to use this

### ISSUE THREAD

**Issue by alienbogart** [sunaku/vim-shortcut#5]
I'm sorry, but I read everything and I still don't know how to use this. How / where can I set a shortcut for later access? If I add something like `Shortcut! keys description` to my ini.vim I get an error message:

```
Error detected while processing ~/.config/nvim/plugin/shortcuts.vim:
line    1:
E492: Not an editor command: shortcut <C-s> save all buffers
E492: Not an editor command: shortcut <C-s> save all buffers
```
How can I save and restore the shortcuts?

**Comment by sunaku** [comment]
You need to load the plugin first before you can use the `Shortcut` command:
```vim
source location/where/you/downloaded/this/plugin/shortcut.vim
```

The commands are case sensitive, so fully lowercase `shortcut` will not work.

**Comment by alienbogart** [comment]
Okay, I learned how to use it, but not completely. If I run `:Shortcut! n<M-u> add after next word`, the shortcut is created and it is accessible. But when I reopen neovim, the shortcut is gone - even after I source `shortcut.vim`. If try adding without the !, get this error:
```
Error detected while processing function <SNR>22_shortcut_command[4]..<SNR>22_handle_define_command[1]..ShortcutParseD
efineCommand[1]..<SNR>22_split_description_and_definition:                                                            
line    3:                                                                                                            
E605: Exception not caught: expected "<description> <map-command>" but got 'n<M-u> add after next word'               
Error detected while processing function <SNR>22_shortcut_command:                                                    
line    4:                                                                                                            
E171: Missing :endif                                                                                                  
Press ENTER or type command to continue  
```
I read your docs, but I still can't figure out to to make it work. Can you help me with that?

Here's my configs:

nvim --version: NVIM v0.2.3-879-gce3bc12e2
Vim (version: ) behaves differently? I don't have Vim on this machine.
Operating system/version: MX Linux 17
Terminal name/version: xfce4-terminal 0.8.3 (Xfce 4.12)
$TERM: xterm-256color

these are my [configuration files](https://github.com/mrbig033/nvim)

**Comment by alienbogart** [comment]
I was able to create a shortcut using `:Shortcut` (no !), but it gets erased anyway.

**Comment by sunaku** [comment]
Once registered, shortcuts only exist in vim's memory: they are not automatically persisted across vim instances (just like most of vim's normal `:set` settings).  Therefore, to enable persistence, you need to save your `:Shortcut` commands in your vimrc (or manually load them into vim) so that they are registered each time you start up vim.  This behavior is exactly like your vimrc file: in order to persist your vim settings, you have to add them to your vimrc; otherwise, they will be lost when you restart vim.

**Comment by sunaku** [comment]
For example, [here is a file](https://github.com/sunaku/.vim/blob/qwerty/bundle/motion/unimpaired.vim) that contains shortcut definitions.  This file is loaded into vim as part of my vimrc.  Consequently, these shortcuts are automatically registered (and thus available for use) whenever I run vim.

**Comment by alienbogart** [comment]
Okay, thanks, now it worked. Could I suggest you make those things more clear on your readme, on your help and on the documentation? I had tried to do that before, but your plugin has some peculiarities. First, you had to explain me that I had to import the shortcuts manually myself. This time I installed it using `vim-plug`, and had to add (based on your instructions) `  so ~/.config/nvim/plugins/plugged/vim-shortcut/plugin/shortcut.vim` to my `init.vim` for it to work at all. My plugin configuration is not on my init.vim, it's on another file that I source from it, but sill: I never had to do that with any plugin I have ever used. I have 22 plugins and have use many others in the past.

I also had to figure out but myself the syntax that goes on the init.vim, since it looks like adding
`Shortcut! [a       (unimpaired) go to previous argument`
works, but
`Shortcut [a       (unimpaired) go to previous argument`
does not work. Why is that?

All these are **NOT** a critic at your plugin, as far as I can tell it works as intended. But it's hard to configure it without clearer and more extensive instructions.

There are no other plugins like yours, it's a GREAT IDEA and it's WELL IMPLEMENTED, so it's very weird for me there's not more people using it. My suggestion is: improve your documentation, like, a lot! :)

I am **not** a programmer and don't have any kind of specialized expertise in computer science or things like that, but I am very invested user of Vim and Linux operating systems. English is not my first languages, but nevertheless: **I can help you with documentation if you want!**

**Comment by sunaku** [comment]
The reason you had to manually add the `:source` command to your init.vim file is because vim-plug does not immediately load a plugin when you run a `:Plug` command!  Instead, it collects all of your `:Plug` commands and loads them all in one shot at the very end, when you call the `plug#end()` function.  This strangeness has nothing to do with my plugin: instead, this is an idiosyncrasy of vim-plug itself.

True, there is a syntax difference between the `:Shortcut` command called with a bang (!) versus without.  The README is not the official documentation (it's just a convenience / starter guide) so you won't find this difference explained in very much detail in the README.  Instead, see the actual API documentation in the `doc/` folder https://github.com/sunaku/vim-shortcut/blob/master/doc/shortcut.txt#L99 or run `:help shortcut` inside vim to reach it.

**Comment by sunaku** [comment]
@mrbig033 You're welcome to submit a pull request with your proposed documentation improvements. :smiley_cat:

**Comment by jkroes** [comment]
New vim user here! I think this plugin could be most helpful for others like me. Do I need a file of shortcuts to generate a list of shortcuts when running :Shortcuts? This runs but doesn't produce any ouptut.

**Comment by sunaku** [comment]
That's correct. :+1:  You first need to register your shortcuts using the `:Shortcut` or `:Shortcut!` commands, as demonstrated in the README (see [many real-life examples here](https://github.com/sunaku/.vim/search?q=Shortcut)).  Afterwards, the `:Shortcuts` command will display a menu of all shortcuts you have registered so far.

**Comment by unixbhaskar** [comment]
Nope it still missed proper documentation,,,,,it seems your documentation are messy which restrict people to use wonderful plugin you wrote . I will appreciate, if you put a little more effort to minimize the documentation to just "Install" and "use this way" specifically ...for instance ...after hover through and reading I ended up with this ...not so encouraging spending time on something...

`Error detected while processing /home/bhaskar/.vimrc:
line  100:
E492: Not an editor command: Shortcut show paste mode on or off  nnoremap <F2> :set invpaste paste?<CR>
Pattern not found: shortcuts
line  262:
E492: Not an editor command: Shortcut show shortcut menu and run chosen shortcut noremap <silent> <Leader><Leader> :Shortcuts<Return>
line  265:
E492: Not an editor command: Shortcut fallback to shortcut menu on partial entry noremap <silent> <Leader> :Shortcuts<Return>
Press ENTER or type command to continue
`

**Comment by unixbhaskar** [comment]
More :

`Error detected while processing function <SNR>20_shortcut_menu_command:
line    3:
E117: Unknown function: fzf#wrap
E116: Invalid arguments for function fzf#run
`

Wondering!!

**Comment by unixbhaskar** [comment]
Thanks for the lovely plugin.  :+1:

**Comment by farzadmf** [comment]
@sunaku  I think the part for `source`ing the plugin should be mentioned somewhere in `README`. I know the `README` isn't supposed to be the full documentation. Because what you mentioned that

> it's just a convenience / starter guide

is not true here; you can't even get started if you follow the `README`: you install (I did with vimplug), you define your shortcut, you open vim (neovim in my case), and boom, you get the error.

I was just about to give up on the plugin and consider it as one of the many plugins that promise something and don't deliver, but I think this plugin has a potential and it's a pitty if people don't try it because of a couple of lines are lacking in the `README`.

**Comment by sunaku** [comment]
Thanks everyone for your feedback and suggestions.  I have added the appropriate installation instructions to the README and the Vim `:help` documentation for this plugin now.  Cheers.
